apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
  labels:
    k8s-app: alertmanager
  name: alertmanager
  namespace: ns-monitoring
spec:
  selector:
    k8s-app: alertmanager
  type: NodePort
  ports:
  - name: alertmanager
    protocol: TCP
    port: 9093
    targetPort: 9093
    nodePort: 30093
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: alertmanager
  namespace: ns-monitoring
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: alertmanager
    spec:
      containers:
      - name: alertmanager
        image: ekambaram/alertmanager:sgd
        args:
          - '-config.file=/etc/alertmanager/config.yml'
          - '-storage.path=/alertmanager'
        ports:
        - containerPort: 9093
        imagePullPolicy: IfNotPresent
        env:
        - name: EMAIL_TO
          value: "project-alerts@gmail.com"
        - name: EMAIL_FROM
          value: "project-alerts@gmail.com"
        - name: SENDGRID_USER_NAME
          value: "bot"
        - name: EMAIL_PASSWORD
          value: "welcome1"
        volumeMounts:
          - mountPath: /etc/alertmanager
            name: alertmanager
        livenessProbe:
          httpGet:
            path: /
            port: 9093
          initialDelaySeconds: 30
          timeoutSeconds: 1
      volumes:
        - name: alertmanager
          configMap:
            name: monitoring-cfg
            items:
              - key: config.yml
                path: config.yml
