apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: alertmanager
  name: alertmanager
  namespace: ns-monitoring
spec:
  selector:
    k8s-app: alertmanager
  type: ClusterIP
  ports:
  - name: alertmanager
    port: 9093
    targetPort: 9093
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: alertmanager
  namespace: ns-monitoring
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: alertmanager
    spec:
      containers:
      - name: alertmanager
        image: prom/alertmanager:ALERT_MANAGER_VERSION
        ports:
        - containerPort: 9093
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /etc/alertmanager
            name: alertmanager
        livenessProbe:
          httpGet:
            path: /
            port: 9093
          initialDelaySeconds: 30
          timeoutSeconds: 1
      volumes:
        - name: alertmanager
          configMap:
            name: monitoring-cfg
            items:
              - key: config.yml
                path: config.yml
