version: '3'

services:
  seleniumhub:
  image: selenium/hub:3.4
  ports:
    - 4444:4444
  networks:
    - devops-net
    
  firefox:
  image: selenium/node-firefox:3.4
  depends_on:
    - seleniumhub
  environment:
    - HUB_PORT_4444_TCP_ADDR=seleniumhub
  networks:
    - devops-net
    
 chrome:
  image: selenium/node-chrome:3.4
  depends_on:
    - seleniumhub
  environment:
    - HUB_PORT_4444_TCP_ADDR=seleniumhub
  networks:
    - devops-net
        
networks:
    devops-net:    
