version: '3'

services:
  influx:
    image: influxdb
    ports:
      - 8083:8083    
    volumes:
      - influxdbdata:/var/lib/influxdb
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      GF_SECURITY_ADMIN_PASSWORD: 'password'
      GF_USERS_ALLOW_SIGN_UP: 'false'
    depends_on:
      - influx
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]

  cadvisor:
    image: google/cadvisor
    hostname: '${hostname}'
    command: -logtostderr -docker_only -storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_host=influx:8086
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - influxdb
    deploy:
      mode: global

volumes:
  influxdbdata:
    driver: local
