version: '3'
services:
  eddi:
    image: labsai/eddi:latest
    ports:
      - 7070:7070
    depends_on:
      - mongodb
    environment:
      EDDI_VERSION: 4.1
      EDDI_ENV: production
      EDDI_MEMORY_MIN: 1G
      EDDI_MEMORY_MAX: 1G
      EDDI_JAVA_ENV_MONGODB_HOST: mongodb.hosts=mongodb
    networks:
      - eddi-net
  mongodb:
    image: mongo:3.4    
    volumes:
      - mongodata:/data/db
    networks:
      - eddi-net

volumes:
  mongodata:
    driver: local
  
networks:
  eddi-net:
