apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-jobservice-config
data:
  CORE_SECRET: "o4FZsfWWakNSFBzf"
  JOBSERVICE_SECRET: "MmL06pKJVuBieiU9"
  SECRET_KEY: "3dSegK5DtTbyXblw"
  MAX_JOB_WORKERS: "10"
  LOG_LEVEL: debug
  GODEBUG: netdns=cgo
  CONFIG_PATH: /etc/jobservice/app.conf
  config: |
    appname = jobservice
    runmode = dev
    [dev]
    httpport = 80
