version: "3.3"

services:
  elasticsearch:
    image: elasticsearch:5.5.0
    ports:
      - "9200:9200"
    environment:
      ES_JAVA_OPTS: -Xms1g -Xmx1g    	
    command: elasticsearch -Enetwork.host=0.0.0.0 -Ediscovery.zen.ping.unicast.hosts=elasticsearch    
    ulimits:
      memlock: -1
      nofile:
        hard: 65536
        soft: 65536
      nproc: 65538
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        constraints: [node.role == manager]
    healthcheck:
      test: curl -s http://localhost:9200/_cluster/health?local=true | grep 'green'
      interval: 30s
      retries: 3
      
  kibana:
    image: kibana:5.5.0
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1
    healthcheck:
      test: wget -qO- http://localhost:5601 > /dev/null
      interval: 30s
      retries: 3
  
  logstash:
    image: logstash:5.5.0-alpine  
    ports:
      - "10514:10514/tcp"
      - "10514:10514/udp"
      - "12201:12201/udp"    
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 2

networks:
  elk:
    driver: overlay
    driver_opts:
      encrypted: "true"
      
configs:
  logstash_config:
    file: ./logstash/logstash.conf   
