version: "3.2"



services:

  reverse_proxy:

      image: ekambaram/eshop-proxy

          ports:

                - "80:80"

                      - "443:443"

                          secrets:

                                - source: revprox_cert

                                        target: revprox_cert

                                              - source: revprox_key

                                                      target: revprox_key

                                                          networks:

                                                                - front-tier




