version: '3'

services:
  jenkins:
    image: jenkins:latest
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - ci-net
    volumes:
      - jenkinsdata:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      
volumes:
  jenkinesdata:
    local
    
networks:
  ci-net:
