version: '3'

services:
  jenkins:
    image: jenkins:latest
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - ci-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      
networks:
    ci-net:
      driver: overlay
