kubectl apply -f https://raw.githubusercontent.com/epasham/docker-repo/master/k8s/monitoring/kube-prom/01.crds.yaml
kubectl apply -f https://raw.githubusercontent.com/epasham/docker-repo/master/k8s/monitoring/kube-prom/02.prom-operator.yaml
kubectl apply -f https://raw.githubusercontent.com/epasham/docker-repo/master/k8s/monitoring/kube-prom/03.kube-state-metrics.yaml
kubectl apply -f https://raw.githubusercontent.com/epasham/docker-repo/master/k8s/monitoring/kube-prom/04.node-exporter.yaml
kubectl apply -f https://raw.githubusercontent.com/epasham/docker-repo/master/k8s/monitoring/kube-prom/05.alertmanager.yaml
kubectl apply -f https://raw.githubusercontent.com/epasham/docker-repo/master/k8s/monitoring/kube-prom/06.grafana-dashboards.yaml
kubectl apply -f https://raw.githubusercontent.com/epasham/docker-repo/master/k8s/monitoring/kube-prom/07.grafana.yaml
kubectl apply -f https://raw.githubusercontent.com/epasham/docker-repo/master/k8s/monitoring/kube-prom/08.prom-adapter.yaml
kubectl apply -f https://raw.githubusercontent.com/epasham/docker-repo/master/k8s/monitoring/kube-prom/09.prom.rules.yaml
kubectl apply -f https://raw.githubusercontent.com/epasham/docker-repo/master/k8s/monitoring/kube-prom/10.prometheus.yaml
kubectl apply -f https://raw.githubusercontent.com/epasham/docker-repo/master/k8s/monitoring/kube-prom/11.prom.serviceMonitors.yaml
