version: '3'

services:
  sensu-server:
    image: hiroakis/docker-sensu-server
    ports:
      - 10022:22
      - 13000:3000
      - 4567:4567
      - 5671:5671
      - 15672:15672
    networks:
      - sensu-net

  sensu-client:
    image: ekambaram/sensu-client:v1
    networks:
      - sensu-net

networks:
  sensu-net:
