apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: logging-logstash
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: logging-logstash
    spec:
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:5.3.2
        ports:
        - containerPort: 5000
        env:
        - name: LS_JAVA_OPTS
          value: -Xmx256m -Xms256m
        volumeMounts:
          - name: config-volume
            mountPath: /usr/share/logstash/config
          - name: logstash-pipeline-volume
            mountPath: /usr/share/logstash/pipeline
        resources:
          limits:
            cpu: 1.0
            memory: 500Mi
          requests:
            cpu: 0.5
            memory: 300Mi
      volumes:
      - name: config-volume
        configMap:
          name: logging-cfg
          items:
            - key: logstash.yml
              path: logstash.yml
      - name: logstash-pipeline-volume
        configMap:
          name: logging-cfg
          items:
            - key: logstash.conf
              path: logstash.conf
---
kind: Service
apiVersion: v1
metadata:
  name: logstash-service
  namespace: default
spec:
  selector:
    name: logging-logstash
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
  type: NodePort
