apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: logging-elasticsearch
  namespace: ns-logging
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: logging-elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: ekambaram/elasticsearch:5.3.2
        imagePullPolicy: IfNotPresent
        env:
        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
        ports:
        - containerPort: 9200
          protocol: TCP
        resources:
          # keep request = limit to keep this container in guaranteed class
          limits:
            cpu: 1000m
            memory: 2G
          requests:
            cpu: 1000m
            memory: 1G
---
kind: Service
apiVersion: v1
metadata:
  name: elasticsearch-service
  namespace: ns-logging
spec:
  selector:
    name: logging-elasticsearch
  ports:
  - protocol: TCP
    port: 9200
    targetPort: 9200
  type: NodePort
