apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: logging-kibana
  labels:
    name: logging-kibana
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: logging-kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:5.3.2
        ports:
        - containerPort: 5601
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/kibana/config
      volumes:
      - name: config-volume
        configMap:
          name: logging-cfg
          items:
            - key: kibana.yml
              path: kibana.yml
---
kind: Service
apiVersion: v1
metadata:
  name: kibana-service
  namespace: default
spec:
  selector:
    name: logging-kibana
  ports:
  - protocol: TCP
    port: 5601
    targetPort: 5601
    nodePort: 30601
  type: NodePort
