apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: logging-filebeat
  namespace: ns-logging
  labels:
    name: logging-filebeat
spec:
  template:
    metadata:
      labels:
        name: logging-filebeat
      name: logging-filebeat
    spec:
      # filebeat has to run as root to read logs, since the logs
      # on the host system are all owned by root. this is a little
      # scary, but at least all the host mounts are read-only, to minimize
      # possible damage.
      #securityContext:
        #runAsUser: 0
      containers:
      - name: filebeat
        image: ekambaram/filebeat:5.3.2
        #image: komljen/filebeat
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 50m
            memory: 100Mi
        securityContext:
          privileged: true
          runAsUser: 0
        volumeMounts:
        - name: config-volume
          mountPath: /etc/filebeat
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: config-volume
        configMap:
          name: logging-cfg
          items:
            - key: filebeat.yml
              path: filebeat.yml
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
