version: '3.1'
services:
  web:
    image: chrch/docker-pets:1.0
    deploy:
      mode: replicated
      replicas: 3
    ports:
      - 5000:5000
      - 7000:7000
    healthcheck:
      interval: 10s
      timeout: 2s
      retries: 3
    environment:
      DB: 'db'
      DEBUG: 'False'
      THREADED: 'True'
      ADMIN_PASSWORD_FILE: '/run/secrets/admin_password'
    networks:
      - pets-net
            
  db:
    image: consul:0.7.2
    command: agent -server -ui -client=0.0.0.0 -bootstrap-expect=3 -retry-join=db -retry-join=db -retry-join=db -retry-interval 5s
    deploy:
      replicas: 3
    ports:
      - 8500:8500 
    environment:
      CONSUL_BIND_INTERFACE: 'eth2'
      CONSUL_LOCAL_CONFIG: '{"skip_leave_on_interrupt": true}'
    networks: 
      - pets-net
              
networks:
  pets-net:
  
secrets:
  admin_password:
    external: true
