version: '3'

services:
  master:
    image: ekambaram/elasticsearch
    environment:
      TYPE: MASTER_DATA_CLIENT
      UNICAST_HOSTS: master
      MIN_MASTERS: 1
    ports:
      - "9200:9200"
      - "9300:9300"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
  kibana:
    image: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://master:9200
