version: '3'

services:
  jenkins:
    image: ekambaram/jenkins:ci
    networks:
      - ci-net
    ports:
      - 18080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkinsdata:/var/lib/jenkins
    
volumes:
  jenkinsdata:
    driver: local
    
networks:
  ci-net:
