# Stage-1
FROM alpine/git as clone
ARG url
WORKDIR /app
RUN git clone ${url}

# Stage-2
FROM maven:3.5-jdk-8-alpine as build
ARG project 
WORKDIR /app
COPY --from=clone /app/${project} /app
RUN mvn package

# Stage-3
FROM openjdk:8-jre-alpine as production-env
ARG artifactid
ARG version
ENV artifact ${artifactid}-${version}.jar
WORKDIR /app
COPY --from=build /app/target/${artifact} /app

EXPOSE 8080
ENTRYPOINT ["sh", "-c"]
CMD ["java -jar ${artifact}"]
