version: "3"

services:
  cadvisor:
    image: google/cadvisor:${CADVISOR_VERSION:-v0.25.0}
    networks:
      - prom-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock,readonly
      - /:/rootfs
      - /var/run:/var/run
      - /sys:/sys
      - /var/lib/docker/:/var/lib/docker
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.10'
          memory: 128M
        reservations:
          cpus: '0.10'
	  memory: 64M
	  
   node-exporter:${NODE_EXPORTER_VERSION:-latest}
    image: prom/node-exporter
    networks:
      - prom-net
    volumes:
      - /proc:/host/proc
      - /sys:/host/sys
      - /:/rootfs
    command: -collector.procfs /host/proc -collector.sysfs /host/sys -collector.filesystem.ignored-mount-points "^/(sys|proc|dev|host|etc)($$|/)"
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.10'
          memory: 32M
        reservations:
          cpus: '0.10'
          memory: 16M
          
  prometheus:
    image: ekambaram/prom:${PROMETHEUS_SWARM_VERSION:-1.7.1}
    ports:
      - 9090:9090
    networks:
      - prom-net
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
        reservations:
          cpus: '0.50'
          memory: 128M  

  grafana:
    image: ekambaram/grafana:${GRAFANA_VERSION:-v2}
    ports:
      - 3000:3000
    networks:
      - prom-net
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD:-admin}
	  GF_USERS_ALLOW_SIGN_UP: false
      PROMETHEUS_ENDPOINT: http://prometheus:9090
      IMPORT_DASHBOARDS: Y
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 64M
        reservations:
          cpus: '0.50'
          memory: 32M

  networks:
    prom-net:
