version: "3"

services:
  cadvisor:
    image: google/cadvisor:${CADVISOR_VERSION:-v0.26.1}
    networks:
      - prom-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /:/rootfs
      - /var/run:/var/run
      - /sys:/sys
      - /var/lib/docker/:/var/lib/docker
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.10'
          memory: 128M
        reservations:
          cpus: '0.10'
          memory: 64M
  
  node:
    image: ekambaram/node-exporter:${NODE_EXPORTER_VERSION:-v0.14.0}
    networks:
      - prom-net
    volumes:
      - /proc:/host/proc
      - /sys:/host/sys
      - /:/rootfs
      - /etc/hostname:/etc/host_hostname
    environment:
      NODE_NAME: /etc/host_hostname
    command: -collector.procfs /host/proc -collector.sysfs /host/sys -collector.textfile.directory /etc/node-exporter/ -collectors.enabled 'conntrack,diskstats,entropy,filefd,filesystem,loadavg,mdadm,meminfo,netdev,netstat,stat,textfile,time,vmstat,ipvs' -collector.filesystem.ignored-mount-points "^/(sys|proc|dev|host|etc)($$|/)"
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.10'
          memory: 32M
        reservations:
          cpus: '0.10'
          memory: 16M
          
  prometheus:
    image: ekambaram/prom:${PROMETHEUS_SWARM_VERSION:-1.7.1}
    ports:
      - 9090:9090
    networks:
      - prom-net
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
        reservations:
          cpus: '0.50'
          memory: 128M  

  grafana:
    image: ekambaram/grafana:${GRAFANA_VERSION:-v2}
    ports:
      - 3000:3000
    networks:
      - prom-net
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD:-admin}
      GF_USERS_ALLOW_SIGN_UP: 'false'
      PROMETHEUS_ENDPOINT: http://prometheus:9090
      IMPORT_DASHBOARDS: 'Y'
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 64M
        reservations:
          cpus: '0.50'
          memory: 32M

networks:
  prom-net:
