version: '3.2'
services:
    mongo:
        image: mongo
    mexpress:
        image: mongo-express
        depends_on:
            - "mongo"
        ports:
            - "8081:8081"
        environment:
            ME_CONFIG_OPTIONS_EDITORTHEME: ambiance
