version: '3'

services:
  mongo:
    image: mongo
    command: mongod --smallfiles --oplogSize 128

  rocketchat:
    image: rocketchat/rocket.chat:latest
    environment:
      - PORT=3000
      - ROOT_URL=http://localhost:3000
      - MONGO_URL=mongodb://mongo:27017/rocketchat
    ports:
      - 3000:3000
  
