version: "3"

services:
  
  jenkins-master:
    image: ekambaram/cfg-as-code:v3
    build:
      context: .
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - JENKINS_ADMIN_PASSWORD=admin
      - JENKINS_URL=http://jenkins-master:8080/jenkins
      - CASC_JENKINS_CONFIG=https://raw.githubusercontent.com/epasham/docker-repo/master/ci-cd-ct/cfg-as-code/jenkins.yaml
      - JAVA_OPTS='-Djenkins.install.runSetupWizard=false'
      
  maven:
    image: ekambaram/jenkins-slave-mvn:${TAG:-3.27-1}
    environment:
      - JENKINS_URL=http://jenkins-master:8080
      - JENKINS_AGENT_NAME=maven
        
     
  sonar:
    image: sonarqube:7.1
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres:5432/sonar
      - SONARQUBE_JDBC_USER=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    depends_on:
      - postgres

  postgres:
    image: postgres:9.6.5-alpine
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
