version: '3'

services:
  osticket:
   image: campbellsoftwaresolutions/osticket
   environment:
     MYSQL_HOST: mysql
     MYSQL_PASSWORD: secret
     ADMIN_FIRSTNAME: 'Admin'
     ADMIN_LASTNAME: 'User'
     ADMIN_EMAIL: 'admin@example.com'
     ADMIN_USERNAME: 'ostadmin'
     ADMIN_PASSWORD: 'Admin1'
   ports:
     - 8180:80
   networks:
     - osticket-net

  mysql:
    image: mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - osticket-net
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: osticket
      MYSQL_USER: osticket
      MYSQL_PASSWORD: secret
     
volumes:
  dbdata:
 
networks:
  osticket-net:
