version: '3'

services:
  osticket:
   image: matiasvictor/docker-osticket
   environment:
     USE_MEMCACHE: 'y'
   ports:
    - 8180:80
   networks:
    - osticket-net

  mysql:
    image: mysql:5.7
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
    volumes:
      - dbdata:/var/lib/mysql
    networks:
     - osticket-net
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: osticket
      MYSQL_USER: osticket
      MYSQL_PASSWORD: osticket
      
  memcached:
    image: bitnami/memcached:latest
    networks:
     - osticket-net
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      OST_HOST: mysql
      OST_PORT: 3306
      OST_USER: osticket
    ports:
     - 8181:80
    networks:
     - osticket-net
     
networks:
  osticket-net:
