version: '3'

services:
  osticket:
   image: campbellsoftwaresolutions/osticket
   environment:
     MYSQL_HOST: mysql
     MYSQL_PASSWORD: secret
     ADMIN_USERNAME: ostadmin
     ADMIN_PASSWORD: Admin1
   ports:
     - 8180:80
   networks:
     - osticket-net

  mysql:
    image: mysql:5.7
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - osticket-net
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: osticket
      MYSQL_USER: osticket
      MYSQL_PASSWORD: secret
            
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: osticket
    ports:
      - 8181:80
    networks:
      - osticket-net
     
volumes:
  dbdata:
 
networks:
  osticket-net:
