apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: harbor
spec:
  rules:
  - host: {{hostname}}
    http:
      paths:
      - path: /
        backend:
          serviceName: core
          servicePort: 80
      - path: /v2
        backend:
          serviceName: registry
          servicePort: repo
      - path: /service
        backend:
          serviceName: core
          servicePort: 80

