version: '3'

services:
  mariadb:
    image: bitnami/mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'dbdata:/bitnami'
    networks:
      - shop-net
      
  prestashop:
    image: bitnami/prestashop
    environment:
      PRESTASHOP_HOST: 127.0.0.1
    ports:
      - 80:80
      - 443:443
    volumes:
      - appdata:/bitnami
    depends_on:
      - mariadb
    networks:
      - shop-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_USER: root
    ports:
      - '8081:80'
    networks:
      - shop-net

volumes:
  dbdata:
    driver: local
  appdata:
    driver: local
 
networks:
  shop-net:
